# Generated by Django 2.2 on 2019-05-25 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produced_at', models.CharField(blank=True, max_length=255, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(choices=[('0', '*'), ('1', '**'), ('2', '***'), ('3', '****'), ('4', '*****')], max_length=1)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('wiki_link', models.URLField()),
                ('picture_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('founding_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2999), django.core.validators.MinValueValidator(1000)])),
                ('founding_country', models.CharField(blank=True, max_length=2, null=True)),
                ('is_active', models.BooleanField()),
                ('rating', models.CharField(choices=[('0', '*'), ('1', '**'), ('2', '***'), ('3', '****'), ('4', '*****')], max_length=1)),
                ('wiki_link', models.URLField()),
                ('picture_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country_of_origin', models.CharField(blank=True, max_length=2, null=True)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2999), django.core.validators.MinValueValidator(1000)])),
                ('wiki_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(choices=[('0', '*'), ('1', '**'), ('2', '***'), ('3', '****'), ('4', '*****')], max_length=1)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wiki_link', models.URLField()),
                ('picture_link', models.URLField(blank=True, null=True)),
                ('album', models.ManyToManyField(blank=True, null=True, to='music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
