# Generated by Django 2.2 on 2019-06-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20190531_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_count', models.IntegerField(editable=False)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(blank=True, choices=[('0', '*'), ('1', '**'), ('2', '***'), ('3', '****'), ('4', '*****')], max_length=1)),
                ('songs', models.ManyToManyField(to='music.Song')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
