# Generated by Django 2.2 on 2019-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='listen_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
