# Generated by Django 2.2 on 2019-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190604_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='listen_latest',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
