# Generated by Django 2.2 on 2019-06-04 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_playlist_listen_latest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('name', 'user')},
        ),
    ]
